package_path: assets
gzip_assets: on
javascript_compressor: yui

javascripts:
  all:
    - build/javascripts/jquery-1.6.js
    - build/javascripts/site.js

stylesheets:
  all:
      - build/stylesheets/bootstrap-responsive.min.css
      - build/stylesheets/bootstrap.min.css
      - build/stylesheets/main.css
